version: '3.6'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: noxart
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: noxart
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: noxart
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  rpc:
    build:
      dockerfile: Dockerfile-rpc
      context: .
    tty: true
    ports:
      - "8500:8500"
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      WAIT_HOSTS: mongo:27017
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
  api:
    build:
      dockerfile: Dockerfile-api
      context: .
    tty: true
    ports:
      - "8501:8501"
    depends_on:
      - rpc
